<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INVENTORY REPORT</title>

    <!-- 💡 Ginamit ang eksaktong Bootstrap link mo para lumabas ang borders -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        @media print {
            table {
                width: 100%;
            }

            th,
            td {
                white-space: nowrap;
                vertical-align: middle;
            }
        }
    </style>
</head>
 

<body class="container-fluid p-4">
    <div class="text-center mb-4">

    <h2 class="mb-1">
        BizzSoft Inventory Management System
    </h2>

    <h4 class="mb-3">
        CURRENT INVENTORY STATUS REPORT
    </h4>

    <p class="mb-1">
        <strong>Printed:</strong>
        {{ now()->format('F d, Y h:i A') }}
    </p>

    @if(request('search') || request('category'))
        <p class="mb-0">
            <strong>Filters Applied:</strong>
            @if(request('search')) "Search: {{ request('search') }}" @endif
            @if(request('category')) | Category Filter Active @endif
        </p>
    @endif

</div>

<hr class="mb-4">


<h5 class="mb-3">
    SUMMARY
</h5>

<table class="table table-bordered w-50 mb-4">

    <tr>
        <th>Total Products</th>
        <td>{{ $totalProducts }}</td>
    </tr>

    <tr>
        <th>Total Stock</th>
        <td>{{ $totalStock }}</td>
    </tr>

    <tr>
        <th>Low Stock Items</th>
        <td>{{ $lowStockProducts }}</td>
    </tr>

    <tr>
        <th>Out of Stock Items</th>
        <td>{{ $outOfStockProducts }}</td>
    </tr>

</table>

<hr>

<hr class="mb-4">

<h5 class="mb-3">
    INVENTORY DETAILS
</h5>


<table class="table table-bordered table-sm">

    <thead>
    <tr>
        <th>Product</th>
        <th>Category</th>
        <th class="text-end">Stock</th>
        <th class="text-end">Reorder Level</th>
        <th class="text-center">Status</th>
    </tr>
</thead>

    <tbody>

    @forelse($products as $product)

        <tr>
            <td class="fw-bold text-nowrap">{{ $product->name }}</td>

            <td>{{ $product->category->category_name ?? 'Uncategorized' }}</td>

            <td class="text-end">{{ $product->stock }} pcs</td>

            <td class="text-end text-muted text-nowrap">{{ $product->reorder_level }} pcs limit</td>

            <td class="text-center text-nowrap">
                @if($product->stock == 0)
                    ❌ Out of Stock
                @elseif($product->stock <= $product->reorder_level)
                    ⚠️ Low Stock
                @else
                    ✅ In Stock
                @endif
            </td>
        </tr>

    @empty

        <tr>
            <td colspan="5" class="text-center">
             No products found in inventory.
            </td>
        </tr>

    @endforelse

    </tbody>

</table>

<hr class="mt-4">

<div class="d-flex justify-content-between">

    <small class="text-muted">
        Generated by:
        {{ auth()->user()->name }}
    </small>

    <small class="text-muted">
        Generated on:
        {{ now()->format('F d, Y h:i A') }}
    </small>

</div>

<div class="text-center mt-3">

    <small class="text-muted">

        End of Inventory Report

    </small>

</div>

<script>
    window.onload = function () {
        window.print();
    };
</script>

</body>
</html>
