<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOW STOCK WARNING REPORT</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
    @media print {

        table{
            width:100%;
        }

        th,
        td{
            white-space:nowrap;
            vertical-align:middle;
        }

        .summary-table{
            width:50% !important;
        }

    }
</style>

</head>

<body class="container-fluid p-4">
    <div class="text-center mb-4">

    <h2 class="mb-1">
        BizzSoft Inventory Management System
    </h2>

    <h4 class="mb-3">
        LOW STOCK WARNING REPORT
    </h4>

    <p class="mb-1">
        <strong>Printed:</strong>
        {{ now()->format('F d, Y h:i A') }}
    </p>

    @if(request('search'))
        <p class="mb-0">
            <strong>Filters Applied:</strong>
            "Search: {{ request('search') }}"
        </p>
    @endif

</div>

<hr class="mb-4">


<h5 class="mb-3">
    SUMMARY
</h5>

<table class="table table-bordered summary-table w-50 mb-4">

    <tr>
        <th>Low Stock Products</th>
        <td>{{ $totalLowStockProducts }}</td>
    </tr>

    <tr>
        <th>Total Low Stock Quantity</th>
        <td>{{ $totalLowStockQuantity }} pcs</td>
    </tr>

</table>

<hr>
<p class="text-muted small">
Products listed below have reached or fallen below their configured safety stock level and may require replenishment.
</p>

<hr class="mb-4">

<h5 class="mb-3">
    CRITICAL INVENTORY DETAILS
</h5>


<table class="table table-bordered table-sm">

    <thead>
    <tr>
        <th>Critical Item</th>
        <th>Category</th>
        <th class="text-end">Remaining Stock</th>
        <th class="text-end">Safety Threshold</th>
    </tr>
</thead>

    <tbody>

    @forelse($lowStockProducts as $product)

        <tr>
            <td class="fw-bold">{{ $product->name }}</td>

            <td>{{ $product->category->category_name ?? 'Uncategorized' }}</td>

            <td class="text-end">
                {{ $product->stock }} pcs
            </td>

            <td class="text-end text-muted">
                {{ $product->reorder_level }} pcs limit
            </td>
        </tr>

    @empty

        <tr>
            <td colspan="4" class="text-center">
             No low stock products found.
            </td>
        </tr>

    @endforelse

    </tbody>

</table>

<hr class="mt-4">

<div class="d-flex justify-content-between">

    <small class="text-muted">
        Generated by:
        {{ auth()->user()->name }}
    </small>

    <small class="text-muted">
        Generated on:
        {{ now()->format('F d, Y h:i A') }}
    </small>

</div>

<div class="text-center mt-3">

    <small class="text-muted">

        End of Low Stock Warning Report

    </small>

</div>

<script>
    window.onload = function () {
        window.print();
    };
</script>

</body>
</html>
