<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Shared Print CSS -->
    <style>
    @media print {

        table{
            width:100%;
        }

        th,
        td{
            white-space:nowrap;
            vertical-align:middle;
        }

        .summary-table{
            width:50% !important;
        }

    }
</style>

    <!-- Dynamic Title -->
    <title>@yield('title', 'System Report')</title>
</head>
<body class="container-fluid py-4">

    <!-- Company Header -->
    <div class="text-center mb-4">
        <h2 class="mb-1">BizzSoft Inventory Management System</h2>
        <h4 class="mb-3 text-uppercase">@yield('report_heading')</h4>

        <!-- Printed Date -->
        <p class="mb-1">
            <strong>Printed:</strong> {{ now()->format('F d, Y h:i A') }}
        </p>

         
    </div>

    <hr class="mb-4">

    <!-- @yield('content') -->
    <main>
        @yield('content')
    </main>

    <hr class="mt-4">

    <!-- Shared Footer -->
    <div class="d-flex justify-content-between">
        <small class="text-muted">
            Generated by: {{ auth()->user()->name ?? 'System Admin' }}
        </small>
        <small class="text-muted">
            Generated on: {{ now()->format('F d, Y h:i A') }}
        </small>
    </div>

    

    <!-- Print Script -->
    <script>
        window.onload = function () {
            window.print();
        };
    </script>
</body>
</html>
