name: BizzSoft Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 145.79.28.207
          username: u180948312
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd /home/u180948312/laravel_app

            echo "Current Directory:"
            pwd

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing Composer Dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "Deployment Step 2 Complete!"